core/urls.py
from django.contrib import admin
from django.urls import path, include
from peserta import views

urlpatterns = [
    path('', views.Dashboard.as_view()),
    path('kontrol/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('input/', views.formInput),
    # path('delete/<int:id>', views.deleteData),

    path('programlist', views.ListProgram.as_view(), name='list-program'),
    path('programnew', views.CreateProgram.as_view(), name='new-program'),
    path('programedit/<int:pk>', views.EditProgram.as_view(), name='edit-program'),
    path('programdelete/<int:id>', views.DeleteProgram.as_view(), name='delete-program'),

    path('pendaftaran', views.CreatePendaftaran.as_view(), name='new-pendaftaran'),

    path('peserta', views.PesertaList.as_view(), name='list-peserta'),

    path('kelas', views.KelasList.as_view(), name='list-kelas'),
    path('kelasnew', views.CreateKelas.as_view(), name='new-kelas'),

    path('trainer', views.TrainerList.as_view(), name='list-trainer'),
    path('trainernew', views.CreateTrainer.as_view(), name='new-trainer'),

    path('tambahpendaftar/<int:id>', views.TambahKePendaftaran.as_view()),

]

peserta/models.py
from django.db import models
from django.contrib.auth.models import User


KOTA = (
    ('mataram', 'Mataram'),
    ('gerung', 'Gerung'),
    ('praya', 'Praya'),
    ('selong', 'Selong'),
    ('tanjung', 'Tanjung'),
)

AGAMA = (
    ('islam', 'Islam'),
    ('Kristen', 'Kristen'),
    ('hindu', 'Hindu'),
    ('budha', 'Budha'),
    ('konghucu', 'Konghucu'),
)

KELAMIN = (
    ('L', 'Laki'),
    ('P', 'Perempuan'),
)

class Peserta(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True, related_name='peserta_user')
    nama_peserta = models.CharField(max_length=255, blank=False, null=False)
    kelamin = models.CharField(max_length=2, choices=KELAMIN, blank=False, null=False)
    tempat_lahir = models.CharField(max_length=30, blank=False, null=False)
    tgl_lahir = models.DateField(blank=False, null=False)
    nomor_handphone = models.CharField(max_length=15, blank=True, null=True)
    agama = models.CharField(max_length=255, choices=AGAMA, blank=False, null=False)
    email = models.EmailField(max_length=255, blank=False, null=False)
    sosmed = models.CharField(max_length=255, blank=False, null=False)
    pendidikan_akhir = models.CharField(max_length=255, blank=True, null=True)
    kota = models.CharField(max_length=255, choices=KOTA, blank=False, null=False)
    alamat = models.TextField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = "Form Peserta"
        verbose_name_plural = "Data Peserta"

    def __str__(self):
        return self.nama_peserta


class Program(models.Model):
    nama_program = models.CharField(max_length=255, blank=True, null=True)
    biaya = models.DecimalField(max_digits=15, decimal_places=2)
    keterangan = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.nama_program


class Trainer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    nama_trainer = models.CharField(max_length=255, blank=True, null=True)
    kelamin = models.CharField(max_length=2, choices=KELAMIN, blank=True, null=True)
    tempat_lahir = models.CharField(max_length=30, blank=True, null=True)
    tgl_lahir = models.DateField(blank=True, null=True)
    nomor_handphone = models.CharField(max_length=15, blank=True, null=True)
    agama = models.CharField(max_length=255, choices=AGAMA, blank=False, null=False)
    email = models.EmailField(max_length=255, blank=True, null=True)
    sosmed = models.CharField(max_length=255, blank=True, null=True)
    pendidikan_akhir = models.CharField(max_length=255, blank=True, null=True)
    kota = models.CharField(max_length=255, choices=KOTA, blank=True, null=True)
    alamat = models.TextField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = "Form Trainer"
        verbose_name_plural = "Data Trainer"

    def __str__(self):
        return self.nama_trainer


class Pendaftaran(models.Model):
    peserta = models.ForeignKey(Peserta, on_delete=models.SET_NULL, blank=True, null=True)
    program = models.ForeignKey(Program, on_delete=models.SET_NULL, blank=True, null=True)
    is_register= models.BooleanField(default=True) # true = belum punya kelas, false = sudah punya kelas
    keterangan = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.peserta.nama_peserta
    


class Kelas(models.Model):
    nama_kelas = models.CharField(max_length=255, blank=True, null=True)
    pendaftaran = models.ManyToManyField(Pendaftaran)
    # peserta = models.ForeignKey(Peserta, on_delete=models.SET_NULL, blank=True, null=True)
    program = models.ForeignKey(Program, on_delete=models.SET_NULL, blank=True, null=True)
    trainer = models.ManyToManyField(Trainer)
    # is_active = models.BooleanField(default=True)
    keterangan = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.nama_kelas

peserta/forms.py
from django import forms
from peserta.models import Peserta, Program, Trainer, Kelas, Pendaftaran


class TrainerForm(forms.ModelForm):
    class Meta:
        model = Trainer
        exclude = ('user',)
        widgets = {
            'tgl_lahir': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(TrainerForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget\
                .attrs['class'] = 'form-control input-sm'


class FormPeserta(forms.ModelForm):
    program_query = Program.objects.all().order_by('nama_program')
    program = forms.ModelChoiceField(queryset=program_query)

    class Meta:
        model = Peserta
        exclude = ('user',)
        widgets = {
            'tgl_lahir': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(FormPeserta, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget\
                .attrs['class'] = 'form-control input-sm'


class ProgramForm(forms.ModelForm):
    class Meta:
        model = Program
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProgramForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            if visible.name == "name":
                visible.field.widget\
                .attrs['autofocus'] = 'autofocus'

            visible.field.widget\
                .attrs['class'] = 'form-control input-sm'


class KelasForm(forms.ModelForm):
    class Meta:
        model = Kelas
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(KelasForm, self).__init__(*args, **kwargs)

        self.fields['trainer']\
            .queryset = Trainer.objects.all()

        self.fields['pendaftaran']\
            .queryset = Pendaftaran.objects.filter(is_register=True)
        
        for visible in self.visible_fields():
            if visible.name == "trainer":
                visible.field.widget\
                .attrs['multiple'] = 'multiple'

            visible.field.widget\
                .attrs['class'] = 'form-control input-sm'


class TambahPendaftaranForm(forms.Form):
    program_query = Program.objects.all().order_by('nama_program')
    program = forms.ModelChoiceField(queryset=program_query)

    def __init__(self, *args, **kwargs):
        super(TambahPendaftaranForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():

            visible.field.widget\
                .attrs['class'] = 'form-control input-sm'

peserta/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from .forms import FormPeserta, ProgramForm, KelasForm, TrainerForm, TambahPendaftaranForm
from .models import Peserta, Program, Pendaftaran, Kelas, Trainer
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic, View
from django.contrib.auth.models import User
from core.lib import useracak
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# @method_decorator(login_required, name='dispatch')
class Dashboard(LoginRequiredMixin, generic.TemplateView):
    template_name = 'layout/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['hi'] = "Welcome to my aplication"

        return context


class ListProgram(generic.ListView):
    model = Program


class FormMixin(object):
    form_class = ProgramForm
    model = Program
    success_url = reverse_lazy('list-program')


class CreateProgram(FormMixin, generic.CreateView):
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["label"] = "Buat Program Baru"

        return context
  

class EditProgram(FormMixin, generic.UpdateView):
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['label'] = "Edit Program"

        return context


class DeleteProgram(View):
    def get(self, req, *args, **kwargs):
        obj = get_object_or_404(Program, id=kwargs['id'])
        obj.delete()

        return redirect('list-program')


class CreatePendaftaran(View):
    def get(self, request):
        form = FormPeserta
        template_name = 'peserta/pendaftaran_form.html'

        return render(request, template_name, {"form": form, "label": "Pendaftaran Baru"})


    def post(self, request):
        form = FormPeserta(request.POST or None)
        template_name = 'peserta/pendaftaran_form.html'

        if form.is_valid():
            peserta = form.save(commit=False)
            user = User()
            user.username = useracak()
            user.is_staff = True
            user.set_password(user.username)
            user.save()

            peserta.user = user
            peserta.save()

            pendaftaran = Pendaftaran()
            pendaftaran.peserta = peserta
            pendaftaran.program = Program.objects.get(pk=request.POST['program'])
            pendaftaran.save()
            
            return redirect('/')

        return render(request, template_name, {"form": form, "label": "Pendaftaran Baru"})



@method_decorator(login_required, name='dispatch')
class PesertaList(generic.ListView):
    model = Peserta
    def get_queryset(self):
        return self.model.objects.all().order_by('-id')


class KelasList(generic.ListView):
    model = Kelas


# class CreateKelas(generic.CreateView):
class CreateKelas(View):
    # form_class = KelasForm
    # model = Kelas
    # success_url = reverse_lazy('list-kelas')

    # def form_valid(self, form):
    #     kelas = form.save(commit=False)
    #     print(kelas.pendaftaran)
    def get(self, request):
        form = KelasForm
        return render(request, "peserta/kelas_form.html", {"form": form})

    def post(self, request):
        form = KelasForm(request.POST or None)
        if form.is_valid():
            kelas = form.save(commit=False)

            for dt in form.cleaned_data['pendaftaran']:
                Pendaftaran.objects.filter(id=dt.id).update(is_register=False)

            kelas.save()

            return redirect('list-kelas')

        return render(request, "peserta/kelas_form.html", {"form": form})


class TrainerList(generic.ListView):
    model = Trainer


class CreateTrainer(generic.CreateView):
    form_class = TrainerForm
    model = Trainer
    success_url = reverse_lazy('list-trainer')

    def form_valid(self, form):
        trainer = form.save(commit=False)
        
        userTrainer = User()
        userTrainer.username = useracak()
        userTrainer.is_staff = True
        userTrainer.set_password(userTrainer.username)
        userTrainer.save()

        trainer.user = userTrainer
        trainer.save()

        return super(CreateTrainer, self).form_valid(form)


class TambahKePendaftaran(View):
    def get(self, request, id):
        data = {
            "peserta": Peserta.objects.get(id=id),
            "form": TambahPendaftaranForm,
        }

        return render(request, "peserta/tambah_ke_pendaftaran.html", data)

    def post(self, request, id):
        peserta = Peserta.objects.get(id=id)
        program = Program.objects.get(id=int(request.POST['program']))
        pendaftaran = Pendaftaran()
        pendaftaran.peserta = peserta
        pendaftaran.program = program
        pendaftaran.save()

        return redirect('list-peserta')


    

templates/peserta/form_input.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">List Data</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a href="#">Input Data</a></li>
        </ol>
    </nav>
    
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}

    <h2>Form Input Data</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <table class="table table-striped">
            {{form.as_table}}
            <tr>
                <td>
                    <button class="btn btn-warning" type="submit">Simpan</button>
                </td>
            </tr>
        </table>
    </form>
</div>

templates/peserta/kelas_form.html
{% extends "layout/index.html" %}

{% block container %}
    <h4>{{label}}</h4>
    <form method="POST" action="">
        {% csrf_token %}
        <table class="table table-bordered">
            {{ form.as_table }}
            <tr>
                <td><input type="submit" class="btn btn-primary"></td>
            </tr>
        </table>
    </form>
{% endblock container %}

templates/peserta/kelas_list.html
{% extends "layout/index.html" %}

{% block container %}
    <h3>Data Kelas</h3>
    <a style="float: right;" href="{% url 'new-kelas' %}" class="btn btn-success btn-sm">Tambah Data</a><br /><br />
    <table class="table table-hover table-striped table-bordered">
        <tr>
            <th width="5%">No.</th>
            <th width="">Nama Kelas</th>
            <th width="">Peserta</th>
            <th width="">Program</th>
            <th width="">Trainer</th>
        </tr>
        {% for data in object_list %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{data.nama_kelas}}</td>
                <td>
                    {% for peserta in data.pendaftaran.all %}
                        {{ peserta.peserta }} |
                    {% endfor %}
                </td>
                <td>{{ data.program.nama_program }}</td>
                <td>
                    {% for trainer in data.trainer.all %}
                        {{ trainer.nama_trainer }} |
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock container %}

templates/peserta/list_data.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"><a href="#">List Data</a></li>
          <li class="breadcrumb-item"><a href="/input">Input Data</a></li>
        </ol>
    </nav>
    <h2>List Data</h2> 
    <table class="table table-hover table-striped table-bordered">
        <tr>
            <th width="5%">No.</th>
            <th width="5%">Proses</th>
            <th width="20%">Nama</th>
            <th width="20%">Program</th>
            <th width="50%">Alamat</th>
        </tr>
        {% for data in peserta %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>
                    <a href="delete/{{data.id}}" class="btn btn-danger btn-sm">Delete</a>
                </td>
                <td>{{data.nama}}</td>
                <td>{{data.program}}</td>
                <td>{{data.alamat}}</td>
            </tr>
        {% endfor %}
    </table>
</div>

templates/peserta/pendaftaran_form.html
{% extends "layout/index.html" %}

{% block container %}
    <h4>{{label}}</h4>
    <form method="POST" action="">
        {% csrf_token %}
        <table class="table table-bordered">
            {{ form.as_table }}
            <tr>
                <td><input type="submit" class="btn btn-primary"></td>
            </tr>
        </table>
    </form>
{% endblock container %}

templates/peserta/peserta_list.html
{% extends "layout/index.html" %}

{% block container %}
    <h3>Data Peserta</h3>
    <a style="float: right;" href="{% url 'new-program' %}" class="btn btn-success btn-sm">Tambah Data</a><br /><br />
    <table class="table table-hover table-striped table-bordered">
        <tr>
            <th width="">No.</th>
            <th width="">Nama</th>
            <th width="">Username</th>
            <th width="">Kelamin</th>
            <th width="">Tempat/Tanggal Lahir</th>
            <th width="">Nomor HP</th>
            <th width="">Alamat</th>
            <th width="">
                Proses
            </th>
        </tr>
        {% for data in object_list %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{data.nama_peserta}}</td>
                <td>{{data.user.username}}</td>
                <td>{{data.kelamin}}</td>
                <td>{{data.tempat_lahir}}, {{data.tgl_lahir}}</td>
                <td>{{data.nomor_handphone}}</td>
                <td>{{data.alamat}}</td>
                <td>
                    <a href="/tambahpendaftar/{{data.id}}" class="btn btn-primary btn-sm">Tambah Ke Pendaftar</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock container %}

templates/peserta/program_form.html
{% extends "layout/index.html" %}

{% block container %}
    <h4>{{label}}</h4>
    <form method="POST" action="">
        {% csrf_token %}
        <table class="table table-bordered">
            {{ form.as_table }}
            <tr>
                <td><input type="submit" class="btn btn-primary"></td>
            </tr>
        </table>
    </form>
{% endblock container %}

templates/peserta/program_list.html
{% extends "layout/index.html" %}

{% block container %}
    <h3>Data Program</h3>
    <a style="float: right;" href="{% url 'new-program' %}" class="btn btn-success btn-sm">Tambah Data</a><br /><br />
    <table class="table table-hover table-striped table-bordered">
        <tr>
            <th width="5%">No.</th>
            <th width="5%">Proses</th>
            <th width="20%">Nama</th>
            <th width="20%">Biaya</th>
        </tr>
        {% for data in object_list %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>
                    <a href="{% url 'edit-program' data.id %}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{% url 'delete-program' id=data.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Hapus Data?')">Delete</a>
                </td>
                <td>{{data.nama_program}}</td>
                <td>{{data.biaya}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock container %}

templates/peserta/tambah_ke_pendaftaran.html
{% extends "layout/index.html" %}

{% block container %}
    <h4>Menambah Peserta Lama [{{peserta.nama_peserta}}]</h4>
    <form method="POST" action="">
        {% csrf_token %}
        <table class="table table-bordered">
            <!-- <input type="hidden" name="id" value="{{peserta.id}}"> -->
            {{ form.as_table }}
            <tr>
                <td><input type="submit" class="btn btn-primary"></td>
            </tr>
        </table>
    </form>
{% endblock container %}

{% block js %}
<script>
    $(function(){
        $("#id_program").select2()
    })
</script>
{% endblock js %}

templates/peserta/trainer_form.html
{% extends "layout/index.html" %}

{% block container %}
    <h4>{{label}}</h4>
    <form method="POST" action="">
        {% csrf_token %}
        <table class="table table-bordered">
            {{ form.as_table }}
            <tr>
                <td><input type="submit" class="btn btn-primary"></td>
            </tr>
        </table>
    </form>
{% endblock container %}

templates/peserta/trainer_list.html
{% extends "layout/index.html" %}

{% block container %}
    <h3>Data Trainer</h3>
    <a style="float: right;" href="{% url 'new-trainer' %}" class="btn btn-success btn-sm">Tambah Data</a><br /><br />
    <table class="table table-hover table-striped table-bordered">
        <tr>
            <th width="">No.</th>
            <th width="">Nama</th>
            <th width="">Username</th>
            <th width="">Kelamin</th>
            <th width="">Tempat/Tanggal Lahir</th>
            <th width="">Nomor HP</th>
            <th width="">Alamat</th>
        </tr>
        {% for data in object_list %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{data.nama_trainer}}</td>
                <td>{{data.user.username}}</td>
                <td>{{data.kelamin}}</td>
                <td>{{data.tempat_lahir}}, {{data.tgl_lahir}}</td>
                <td>{{data.nomor_handphone}}</td>
                <td>{{data.alamat}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock container %}